### PR TITLE
List contributions pages

### PR DESCRIPTION
**Pull request by marclll**

### CODE REVIEW

**Review by xavier-campos-diaz — APPROVED** [review]

**Comment by marclll** [comment]
[Main page](https://trello.com/c/exEwaxaB/3-main-page)

**Comment by marclll** [comment]
[New list](https://trello.com/c/DzWvY43I/8-new-list)

**Comment by marclll** [comment]
[Upvote contributions and comments](https://trello.com/c/KwpB3LKV/14-upvote-contributions-and-comments)

**Comment by marclll** [comment]
[Hide contributions and comments](https://trello.com/c/ntD8Mudc/15-hide-contributions-and-comments)

**Pull request merged**
