### PR TITLE
Api interaction

### PR DESCRIPTION
**Pull request by marclll**

### CODE REVIEW

**Review by enrichp — APPROVED** [review]

**Comment by AlbertPG** [comment]
[User API interaction](https://trello.com/c/LNVS6Che/18-user-api-interaction)

**Review by xavier-campos-diaz — APPROVED** [review]

**Comment by AlbertPG** [comment]
[Contribution API interaction](https://trello.com/c/LazFIuPg/20-contribution-api-interaction)

**Comment by AlbertPG** [comment]
[Comment API interaction](https://trello.com/c/JmISwxX0/19-comment-api-interaction)

**Comment by marclll** [comment]
[User API interaction](https://trello.com/c/LNVS6Che/18-user-api-interaction)

**Comment by marclll** [comment]
[Contribution API interaction](https://trello.com/c/LazFIuPg/20-contribution-api-interaction)

**Comment by marclll** [comment]
[Comment API interaction](https://trello.com/c/JmISwxX0/19-comment-api-interaction)

**Pull request merged**
