### PR TITLE
Merge functionalities

### PR DESCRIPTION
**Pull request by marclll**

### CODE REVIEW

**Review by xavier-campos-diaz — APPROVED** [review]

**Comment by marclll** [comment]
[Voted submissions and comments list](https://trello.com/c/IWUHHhkM/23-voted-submissions-and-comments-list)

**Comment by marclll** [comment]
[Hide contributions and comments](https://trello.com/c/ntD8Mudc/15-hide-contributions-and-comments)

**Comment by marclll** [comment]
[Upvote contributions and comments](https://trello.com/c/KwpB3LKV/14-upvote-contributions-and-comments)

**Comment by marclll** [comment]
[Hidden list](https://trello.com/c/RktwYTCH/22-hidden-list)

**Comment by marclll** [comment]
[Ask list](https://trello.com/c/fNIBDDTp/11-ask-list)

**Comment by marclll** [comment]
[New list](https://trello.com/c/DzWvY43I/8-new-list)

**Comment by marclll** [comment]
[Main page](https://trello.com/c/exEwaxaB/3-main-page)

**Comment by marclll** [comment]
[Show list](https://trello.com/c/wts4C2ZZ/12-show-list)

**Comment by marclll** [comment]
[Threads list](https://trello.com/c/1eJGZPCj/9-threads-list)

**Comment by marclll** [comment]
[Submissions list](https://trello.com/c/aQeGYvpm/10-submissions-list)

**Pull request merged**
